---
swagger: "2.0"
info:
  description: "Register Coupon"
  version: "1.0"
  title: "adminCouponOfferAPI"
host: "104.196.165.85:8080"
basePath: "/rest"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /STC_ApiMgmt_Demo_LocBasedCoupon/coupon/admin:
    get:
      description: "Retrieves Coupon information from registry\r\nInput:\r\naccountNumber\
        \ (manadatory) - Partner's Billing Account Number\r\ncouponID (optional) -\
        \ Specific coupon/offer identification (used to pull a specific offer from\
        \ the registry).\r\nOutput:\r\noffers (JSON List) - List of offers that match\
        \ the critieria."
      parameters:
      - name: "accountNumber"
        in: "query"
        required: true
        type: "string"
      - name: "couponID"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_get_$response"
        401:
          description: "Access Denied"
    post:
      description: "Inserts or Updates a coupon to the registry\r\nInput:\r\noffer\
        \ - JSON document with offer details.  If a couponID exists for the account\
        \ already the entry will updated, else it is inserted.\r\n\r\nOutput:\r\n\
        result - Text description of insert/update results.\r\n"
      parameters:
      - in: "body"
        name: "offerDetails"
        required: true
        schema:
          $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.doc:offer"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_post_$response"
        401:
          description: "Access Denied"
    put:
      description: "Inserts or Updates a coupon to the registry\r\nInput:\r\noffer\
        \ - JSON document with offer details.  If a couponID exists for the account\
        \ already the entry will updated, else it is inserted.\r\n\r\nOutput:\r\n\
        result - Text description of insert/update results.\r\n"
      parameters:
      - in: "body"
        name: "offerDetails"
        required: true
        schema:
          $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.doc:offer"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_put_$response"
        401:
          description: "Access Denied"
    delete:
      description: "Removes coupon from Registration\r\nInput:\r\naccountNumber -\
        \ Patner's account used for billing usage of API.\r\ncouponID - Identification\
        \ assigned by partner to the coupon so its distribution reach can be tracked.\r\
        \n\r\nOutput:\r\nresult - Description of the delete action's return."
      parameters:
      - name: "accountNumber"
        in: "query"
        required: true
        type: "string"
      - name: "couponID"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_delete_$response"
        401:
          description: "Access Denied"
definitions:
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_get.criteria:
    required:
    - "gender"
    - "locations"
    - "maxAge"
    - "minAge"
    properties:
      gender:
        type: "string"
      maxAge:
        type: "string"
      minAge:
        type: "string"
      locations:
        type: "array"
        items:
          $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_get.locations"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_delete_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.doc:offer:
    required:
    - "accountNumber"
    - "couponID"
    - "criteria"
    - "expirationDate"
    - "message"
    properties:
      criteria:
        $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_get.criteria"
      accountNumber:
        type: "string"
      couponID:
        type: "string"
      message:
        type: "string"
      expirationDate:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_get.range:
    required:
    - "distance"
    - "uom"
    properties:
      uom:
        type: "string"
      distance:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_get_$response:
    required:
    - "offers"
    properties:
      offers:
        type: "array"
        items:
          $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.doc:offer"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_get.locations:
    required:
    - "latitude"
    - "longitude"
    - "range"
    properties:
      latitude:
        type: "string"
      range:
        $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_get.range"
      longitude:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_put_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.admin:_post_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
