---
swagger: "2.0"
info:
  version: "1.0"
  title: "Customer Billing API - HTTP"
host: "104.196.165.85:25555"
basePath: "/rest"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /STC_ApiMgmt_Demo_BillingApp/billing/customer:
    get:
      parameters:
      - name: "$path"
        in: "formData"
        required: false
        type: "string"
      - name: "$resourceID"
        in: "formData"
        required: false
        type: "string"
      - name: "accountNumber"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp/billing/customer:_get_$response"
        401:
          description: "Access Denied"
    post:
      parameters:
      - name: "$path"
        in: "header"
        required: false
        type: "string"
      - name: "$resourceID"
        in: "header"
        required: false
        type: "string"
      - in: "body"
        name: "customerDetails"
        required: true
        schema:
          $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:customer"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp/billing/customer:_post_$response"
        401:
          description: "Access Denied"
    put:
      parameters:
      - name: "$path"
        in: "header"
        required: false
        type: "string"
      - name: "$resourceID"
        in: "header"
        required: false
        type: "string"
      - in: "body"
        name: "customerDetails"
        required: true
        schema:
          $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:customer"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp/billing/customer:_put_$response"
        401:
          description: "Access Denied"
    delete:
      parameters:
      - name: "$path"
        in: "formData"
        required: false
        type: "string"
      - name: "$resourceID"
        in: "formData"
        required: false
        type: "string"
      - name: "accountNumber"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp/billing/customer:_delete_$response"
        401:
          description: "Access Denied"
definitions:
  STC_ApiMgmt_Demo_BillingApp/billing/customer:_post_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp/billing/customer:_get_$response:
    required:
    - "customerDetails"
    properties:
      customerDetails:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:customer"
  STC_ApiMgmt_Demo_BillingApp/billing/customer:_put_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
      accountNumber:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.doc:company:
    required:
    - "name"
    properties:
      name:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.doc:creditCard:
    required:
    - "cvc"
    - "expiration"
    - "name"
    - "number"
    properties:
      number:
        type: "string"
        format: "password"
      cvc:
        type: "string"
        format: "password"
      name:
        type: "string"
      expiration:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.doc:contact:
    required:
    - "email"
    - "phone"
    properties:
      phone:
        type: "string"
      email:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp/billing/customer:_delete_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.doc:address:
    required:
    - "address1"
    - "address2"
    - "address3"
    - "country"
    - "zip"
    properties:
      zip:
        type: "string"
      country:
        type: "string"
      address3:
        type: "string"
      address2:
        type: "string"
      address1:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.doc:customer:
    required:
    - "address"
    - "billingInfo"
    - "contact"
    - "products"
    - "type"
    properties:
      billingInfo:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:billingInfo"
      address:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:address"
      companyInfo:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:company"
      contact:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:contact"
      type:
        type: "string"
      individualInfo:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:individual"
      accountNumber:
        type: "string"
      products:
        type: "array"
        items:
          $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:product"
  STC_ApiMgmt_Demo_BillingApp.doc:product:
    required:
    - "package"
    - "plan"
    - "type"
    properties:
      package:
        type: "string"
      type:
        type: "string"
      plan:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.doc:billingInfo:
    required:
    - "billingType"
    properties:
      billingType:
        type: "string"
      accountNumber:
        type: "string"
      creditCard:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:creditCard"
  STC_ApiMgmt_Demo_BillingApp.doc:individual:
    required:
    - "firstName"
    - "lastName"
    - "middleName"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      middleName:
        type: "string"
