---
swagger: "2.0"
info:
  description: "Customer Operations."
  version: "1.0"
  title: "customerBillingAPI"
host: "104.196.165.85:25555"
basePath: "/rest"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /STC_ApiMgmt_Demo_BillingApp.billing.customer:
    get:
      description: ""
      parameters:
      - name: "accountNumber"
        in: "formData"
        description: ""
        required: false
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp/billing/customer:_get_$response"
        401:
          description: "Access Denied"
    post:
      description: ""
      parameters:
      - in: "body"
        name: "customerDetails"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:customer"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.billing.customer:_post_$response"
        401:
          description: "Access Denied"
    put:
      description: ""
      parameters:
      - in: "body"
        name: "customerDetails"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:customer"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.billing.customer:_put_$response"
        401:
          description: "Access Denied"
    delete:
      description: ""
      parameters:
      - name: "accountNumber"
        in: "formData"
        description: ""
        required: false
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.billing.customer:_delete_$response"
        401:
          description: "Access Denied"
definitions:
  STC_ApiMgmt_Demo_BillingApp.billing.customer:_post_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.billing.customer:_get_$response:
    required:
    - "customerDetails"
    properties:
      customerDetails:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:customer"
  STC_ApiMgmt_Demo_BillingApp.billing.customer:_put_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
      accountNumber:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.billing.customer:_delete_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_BillingApp.doc:customer:
    required:
    - "address"
    - "applicationId"
    - "billingInfo"
    - "companyInfo"
    - "contact"
    - "products"
    - "type"
    properties:
      billingInfo:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:billingInfo"
      address:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:address"
      companyInfo:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:company"
      contact:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:contact"
      type:
        type: "string"
      applicationId:
        type: "string"
      individualInfo:
        $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:individual"
      accountNumber:
        type: "string"
      products:
        type: "array"
        items:
          $ref: "#/definitions/STC_ApiMgmt_Demo_BillingApp.doc:product"
