---
swagger: "2.0"
info:
  description: "Check Customer Event, if match then distribute coupon"
  version: "1.0"
  title: "distributeCouponAPI"
host: "104.196.165.85:8080"
basePath: "/rest"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:
    get:
      description: "Get eligible offers for a customer."
      parameters:
      - name: "gender"
        in: "query"
        required: true
        type: "string"
      - name: "latitude"
        in: "query"
        required: true
        type: "string"
      - name: "age"
        in: "query"
        required: true
        type: "string"
      - name: "longitude"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_get_$response"
        401:
          description: "Access Denied"
    post:
      description: "Send Offers to Customer."
      parameters:
      - in: "body"
        name: "customerEvent"
        required: true
        schema:
          $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.doc:customerEvent"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_post_$response"
        401:
          description: "Access Denied"
    put:
      description: "Send Offers to Customer."
      parameters:
      - in: "body"
        name: "customerEvent"
        required: true
        schema:
          $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.doc:customerEvent"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_put_$response"
        401:
          description: "Access Denied"
definitions:
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_get.locations:
    required:
    - "latitude"
    - "longitude"
    - "range"
    properties:
      latitude:
        type: "string"
      range:
        $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_get.range"
      longitude:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.doc:offer:
    required:
    - "accountNumber"
    - "couponID"
    - "criteria"
    - "expirationDate"
    - "message"
    properties:
      criteria:
        $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_get.criteria"
      accountNumber:
        type: "string"
      couponID:
        type: "string"
      message:
        type: "string"
      expirationDate:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_put_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_post.location:
    required:
    - "latitude"
    - "longitude"
    properties:
      latitude:
        type: "string"
      longitude:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_post_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.doc:customerEvent:
    required:
    - "age"
    - "customerAddress"
    - "deliveryType"
    - "gender"
    - "location"
    properties:
      customerAddress:
        type: "string"
      gender:
        type: "string"
      deliveryType:
        type: "string"
      location:
        $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_post.location"
      age:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_get.criteria:
    required:
    - "gender"
    - "locations"
    - "maxAge"
    - "minAge"
    properties:
      gender:
        type: "string"
      maxAge:
        type: "string"
      minAge:
        type: "string"
      locations:
        type: "array"
        items:
          $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_get.locations"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_get_$response:
    required:
    - "offersToCustomer"
    properties:
      offersToCustomer:
        type: "array"
        items:
          $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.doc:offer"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.distribute:_get.range:
    required:
    - "distance"
    - "uom"
    properties:
      uom:
        type: "string"
      distance:
        type: "string"
