---
swagger: "2.0"
info:
  version: "1.0"
  title: "monitorCouponUsageAPI"
host: "104.196.165.85:8080"
basePath: "/rest"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:
    get:
      parameters:
      - name: "accountNumber"
        in: "query"
        required: true
        type: "string"
      - name: "couponID"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_get_$response"
        202:
          description: "Accepted"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_get_$response"
        401:
          description: "Access Denied"
    post:
      parameters:
      - name: "incrementBy"
        in: "query"
        required: false
        type: "string"
      - name: "accountNumber"
        in: "query"
        required: true
        type: "string"
      - name: "couponID"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_post_$response"
        202:
          description: "Accepted"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_post_$response"
        401:
          description: "Access Denied"
    put:
      parameters:
      - name: "incrementBy"
        in: "query"
        required: false
        type: "string"
      - name: "accountNumber"
        in: "query"
        required: true
        type: "string"
      - name: "couponID"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_put_$response"
        202:
          description: "Accepted"
          schema:
            $ref: "#/definitions/STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_put_$response"
        401:
          description: "Access Denied"
definitions:
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_post_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_get_$response:
    required:
    - "offersSent"
    properties:
      offersSent:
        type: "string"
  STC_ApiMgmt_Demo_LocBasedCoupon.coupon.monitor:_put_$response:
    required:
    - "result"
    properties:
      result:
        type: "string"
